### ISSUE TITLE
wireless is unavailable

### ISSUE THREAD

**Issue by huangsiyuan924** [NLTD2010/Dell-Inspiron-15-3576-hackintosh#1]

**Comment by NLTD2010** [comment]
what is your wifi card name?

**Comment by hicbowen** [comment]
> what is your wifi card name?

my wireless network card is intel8265, my bluetooth is not work, what can I do?

**Comment by NLTD2010** [comment]
> 
https://www.facebook.com/nguyenlethaiduong2000/
ib me :3
another chat ?

**Comment by NLTD2010** [comment]
Noreply
