### ISSUE TITLE
为啥我的引导进图形界面就黑屏

### ISSUE THREAD

**Issue by jkjoy** [NLTD2010/Dell-Inspiron-15-3576-hackintosh#2]
跑完代码就黑屏。背光亮，用hdmi也可以。就是内屏无解

**Comment by NLTD2010** [comment]
你能说英语吗 ？

**Comment by NLTD2010** [comment]
你的设备的配置是什么？
Eng:  What is your device's specs

**Comment by jkjoy** [comment]
Dell Inspiron 3576

**Comment by NLTD2010** [comment]
Do you have Facebook or telegram or twitter

**Comment by NLTD2010** [comment]
https://www.facebook.com/nguyenlethaiduong2000/
This is my facebook

**Comment by NLTD2010** [comment]
problem noreply
